var annotated_dup =
[
    [ "Datagram", null, [
      [ "Gpio", "classDatagram_1_1Gpio.html", "classDatagram_1_1Gpio" ],
      [ "I2C", "classDatagram_1_1I2C.html", "classDatagram_1_1I2C" ],
      [ "Metadata", "classDatagram_1_1Metadata.html", "classDatagram_1_1Metadata" ],
      [ "SPI", "classDatagram_1_1SPI.html", "classDatagram_1_1SPI" ]
    ] ],
    [ "afe1_status", "structafe1__status.html", "structafe1__status" ],
    [ "afe2_status", "structafe2__status.html", "structafe2__status" ],
    [ "afe3_status", "structafe3__status.html", "structafe3__status" ],
    [ "battery_info", "structbattery__info.html", "structbattery__info" ],
    [ "battery_status", "structbattery__status.html", "structbattery__status" ],
    [ "battery_vt", "structbattery__vt.html", "structbattery__vt" ],
    [ "CanHwSocketData", "structCanHwSocketData.html", null ],
    [ "CanId", "unionCanId.html", null ],
    [ "CanListener", "classCanListener.html", "classCanListener" ],
    [ "CanMessage", "structCanMessage.html", "structCanMessage" ],
    [ "CanQueue", "structCanQueue.html", null ],
    [ "CanScheduler", "classCanScheduler.html", "classCanScheduler" ],
    [ "CanSettings", "structCanSettings.html", "structCanSettings" ],
    [ "cc_info", "structcc__info.html", "structcc__info" ],
    [ "cc_pedal", "structcc__pedal.html", "structcc__pedal" ],
    [ "cc_regen_percentage", "structcc__regen__percentage.html", "structcc__regen__percentage" ],
    [ "cc_steering", "structcc__steering.html", "structcc__steering" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "ClientConnection", "classClientConnection.html", "classClientConnection" ],
    [ "ClientI2CManager", "classClientI2CManager.html", null ],
    [ "ClientSPIManager", "classClientSPIManager.html", null ],
    [ "DatagramGpio", "classDatagramGpio.html", null ],
    [ "DatagramI2C", "classDatagramI2C.html", null ],
    [ "DatagramMetadata", "classDatagramMetadata.html", null ],
    [ "DatagramSPI", "classDatagramSPI.html", null ],
    [ "fast_one_shot_msg", "structfast__one__shot__msg.html", "structfast__one__shot__msg" ],
    [ "GpioAddress", "structGpioAddress.html", null ],
    [ "GpioManager", "classGpioManager.html", "classGpioManager" ],
    [ "I2CManager", "classI2CManager.html", "classI2CManager" ],
    [ "JSONManager", "classJSONManager.html", "classJSONManager" ],
    [ "medium_one_shot_msg", "structmedium__one__shot__msg.html", "structmedium__one__shot__msg" ],
    [ "NTPClient", "classNTPClient.html", "classNTPClient" ],
    [ "NTPPacket", "structNTPPacket.html", "structNTPPacket" ],
    [ "NTPServer", "classNTPServer.html", "classNTPServer" ],
    [ "NTPTime", "structNTPTime.html", "structNTPTime" ],
    [ "Queue", "structQueue.html", "structQueue" ],
    [ "QueueStorage", "structQueueStorage.html", null ],
    [ "Server", "classServer.html", "classServer" ],
    [ "ServerI2CManager", "classServerI2CManager.html", null ],
    [ "ServerSPIManager", "classServerSPIManager.html", null ],
    [ "slow_one_shot_msg", "structslow__one__shot__msg.html", "structslow__one__shot__msg" ],
    [ "SPIManager", "classSPIManager.html", "classSPIManager" ],
    [ "Terminal", "classTerminal.html", "classTerminal" ]
];