var modules =
[
    [ "Autogeneration tools", "group__autogen.html", "group__autogen" ],
    [ "CAN", "group__CAN.html", "group__CAN" ],
    [ "ClientAppMain", "group__ClientAppMain.html", "group__ClientAppMain" ],
    [ "ClientAppCallback", "group__ClientAppCallback.html", "group__ClientAppCallback" ],
    [ "ClientGpioManager", "group__ClientGpioManager.html", "group__ClientGpioManager" ],
    [ "ClientI2CManager", "group__ClientI2CManager.html", "group__ClientI2CManager" ],
    [ "ClientSPIManager", "group__ClientSPIManager.html", "group__ClientSPIManager" ],
    [ "Client_Utils", "group__Client__Utils.html", "group__Client__Utils" ],
    [ "CommandCodes", "group__CommandCodes.html", "group__CommandCodes" ],
    [ "GpioDatagram", "group__GpioDatagram.html", null ],
    [ "I2CDatagram", "group__I2CDatagram.html", null ],
    [ "JSONManager", "group__JSONManager.html", "group__JSONManager" ],
    [ "MetadataDatagram", "group__MetadataDatagram.html", null ],
    [ "NetworkTimeProtocolHelpers", "group__NetworkTimeProtocolHelpers.html", "group__NetworkTimeProtocolHelpers" ],
    [ "SerializationHelpers", "group__SerializationHelpers.html", "group__SerializationHelpers" ],
    [ "SPIDatagram", "group__SPIDatagram.html", null ],
    [ "ThreadHelpers", "group__ThreadHelpers.html", "group__ThreadHelpers" ],
    [ "Logger", "group__Logger.html", "group__Logger" ],
    [ "Queues", "group__Queues.html", "group__Queues" ],
    [ "ServerAppMain", "group__ServerAppMain.html", "group__ServerAppMain" ],
    [ "ServerAppCallback", "group__ServerAppCallback.html", "group__ServerAppCallback" ],
    [ "AppTerminal", "group__AppTerminal.html", "group__AppTerminal" ],
    [ "CanListener", "group__CanListener.html", "group__CanListener" ],
    [ "CanScheduler", "group__CanScheduler.html", "group__CanScheduler" ],
    [ "ServerGpioManager", "group__ServerGpioManager.html", "group__ServerGpioManager" ],
    [ "ServerI2CManager", "group__ServerI2CManager.html", "group__ServerI2CManager" ],
    [ "ServerSPIManager", "group__ServerSPIManager.html", "group__ServerSPIManager" ],
    [ "Server_Utils", "group__Server__Utils.html", "group__Server__Utils" ]
];